### ISSUE TITLE
OXID eShop complains about wrong file permission settings after fresh installation

### ISSUE THREAD

**Issue by floeschie** [OXID-eSales/oxvm_eshop#7] opened 2015-10-22 13:51 UTC
# Description

I've created a new instance, following the quick installation steps described in the README file. I was able to open the eShop in a browser on the host machine, and log in as _admin_ user. The system health check complains about wrong folder/file access rights, so I ssh'd into the VM and did a chmod, but I assume due to mounting options of the shared folder, changes were not applied. Removing write access from the file on the host didn't change anything neither.

# Steps to reproduce

1. Vagrant up a fresh OXID eShop CE as described in the README
1. Open _http://oxideshop.dev/admin_ in the host's browser
1. Login as _admin_ user

# Actual results

- System health check complains about wrong file access rights
- System health check complains about existing setup directory

# Expected result

- System health check does not complain about wrong access rights
- setup directory was renamed or removed

**Comment by reibejoy** [comment] 2015-12-17 14:43
I've never seen an oxid install that did not show that message. I've also tried to get rid of it, but no luck. Seems to be a pretty sticky bug.

**Comment by rezonanc-oxid** [comment] 2016-01-29 10:39
This is a duplicate of https://github.com/OXID-eSales/oxvm_eshop/issues/5.

**Closed by rezonanc-oxid** 2016-01-29 10:39 UTC
Labels: enhancement
