### ISSUE TITLE
Not able to install OXID PE or CE Version 6.0 or 6.1

### ISSUE THREAD

**Issue by clro** [OXID-eSales/oxvm_eshop#43] opened 2019-12-04 12:59 UTC
Hi
I'm trying to install OXID PE Version 6.0 and 6.1 and CE Version 6.0 and 6.1 in oxvm_eshop b-6.1 with no success.

The installation stops with a RuntimeException because the Plugin installation of ocramius/package-versions (1.2.0) failes

` - Installing ocramius/package-versions (1.2.0): Loading from cache
Plugin installation failed, rolling back
  - Removing ocramius/package-versions (1.2.0)
  [RuntimeException]
  Could not delete /var/www/htdocs/oxid615-CE/vendor/ocramius/package-versions/src/PackageVersions:`

I tried it with OS: Windows 7 / VirtualBox 5.2.8 / Vagrant 2.0.2
and OS: Windows 7 / VirtualBox 6.0.14 / Vagrant 2.2.6

Any ideas what causes the problem?
Thanks in advance 
Claudia

**Comment by clro** [comment] 2019-12-04 17:08
Hi
i posted this problem also in OXID forum and a forum Member replied with the following Workaround which helped me install the shop without any further problems:

Workaround for Windows env:
1.	Create new project in terminal as administrator on Windows OS
2.	Finish OXID installation on Windows side but you will have wrong bin files. To fix this go to the next step.
3.	Login into VM via vagrant ssh
4.	Execute in /var/www/{PROJECT_NAME}:
composer clear-cache
rm composer.lock
rm -r vendor
composer update --no-scripts --no-plugins
composer update
5.	Execute:
vendor/bin/oe-eshop-unified_namespace_generator
(without this you will have “ConfigFile” error)

**Comment by Sieg** [comment] 2019-12-09 08:56
Hello @clro, it is mentioned in the documentation to start the terminal with administration rights in case you are using Windows, here: https://github.com/OXID-eSales/oxvm_eshop#quick-start

**Comment by Sieg** [comment] 2019-12-09 09:01
Hello @clro, is the issue only for PE? Can you please provide the full list of commands you are using for starting the box and installing the shop?

**Comment by Sieg** [comment] 2020-01-13 15:50
Hello @clro, closing the question as there is no further communication and clarification regarding the issue.

**Comment by wgmv** [comment] 2020-01-21 13:09
Hi @Sieg I have the same problem - also on Windows 10, vagrant 2.2.6:
Followed the Quickstart installation with CE version

> cd oxvm_eshop
> vagrant up
> vagrant ssh
> composer create-project oxid-esales/oxideshop-project /var/www/oxideshop dev-b-6.1-ce

Error:

```
  - Installing ocramius/package-versions (1.2.0): Loading from cache
Plugin installation failed, rolling back
  - Removing ocramius/package-versions (1.2.0)

  [ErrorException]
  include(/var/www/oxideshop/vendor/ocramius/package-versions/src/PackageVersions/Installer.php): failed to open stream: No such file or directory
```

**Comment by wgmv** [comment] 2020-01-21 13:59
@Sieg this seems to be a bug in virtualbox or vagrant.
More info here https://github.com/Ocramius/PackageVersions/issues/107
and https://github.com/laravel/homestead/issues/1240#issuecomment-513989365

**Comment by patrick-blom** [comment] 2020-04-02 08:03
Hi @Sieg,
I can reproduce this issue also on Ubuntu 18.04 with Vargrant 2.2.7 at the 6.1 and 6.2 release.

The workaround from @clro fixed my problem, but its damn frustrating if the described installation process does not work out of the box. Especially to new eShop developers.

Cheers Patrick

> Hi @Sieg I have the same problem - also on Windows 10, vagrant 2.2.6:
> Followed the Quickstart installation with CE version
> 
> > cd oxvm_eshop
> > vagrant up
> > vagrant ssh
> > composer create-project oxid-esales/oxideshop-project /var/www/oxideshop dev-b-6.1-ce
> 
> Error:
> 
> ```
>   - Installing ocramius/package-versions (1.2.0): Loading from cache
> Plugin installation failed, rolling back
>   - Removing ocramius/package-versions (1.2.0)
> 
>   [ErrorException]
>   include(/var/www/oxideshop/vendor/ocramius/package-versions/src/PackageVersions/Installer.php): failed to open stream: No such file or directory
> ```

**Comment by Sieg** [comment] 2020-04-02 08:13
Hi @patrick-blom! Thanks for the information, we will investigate.

**Comment by PirxDanford** [comment] 2020-04-14 14:19
Hi @patrick-blom sadly I did not find a perfect solution (yet), but could you let me know if using this approach would work for you please:
```
composer create-project oxid-esales/oxideshop-project /tmp/oxideshop dev-b-6.1-ce
cp -r /tmp/oxideshop /var/www
rm -rf /tmp/oxideshop
```

**Comment by patrick-blom** [comment] 2020-04-14 20:42
Hi @PirxDanford 
I tried that approach on the latest master of the vm, that worked for me. 

Cheers Patrick

**Comment by PirxDanford** [comment] 2020-04-15 10:09
Thanks for the feedback - I adapted the quickstart section at https://github.com/OXID-eSales/oxvm_eshop#quick-start which hopefully provides a smoother start for beginners now.

**Closed by PirxDanford** 2020-04-15 10:09 UTC
