### ISSUE TITLE
Eshop doesn't work out of the box (theme problems)

### ISSUE THREAD

**Issue by kaltun** [OXID-eSales/oxvm_eshop#23] opened 2016-10-12 08:03 UTC
Flow theme is not available in initial VM's oxid version so I got error. What I did - I activated Azure theme and problem was solved.
I think Azure theme should be activated or Flow theme should be included in source code.

Requires MUCH time to find out where the problem is! Please fix it, save people's time ;)

**Comment by keywan-ghadami-oxid** [comment] 2016-10-13 06:18
Thank you for reporting, I have got similar reports from others developers. As 
https://github.com/OXID-eSales/oxvm_eshop/issues/21 reports the same issue
Is it ok for you if we close this one?

**Comment by rezonanc-oxid** [comment] 2016-11-17 20:55
The issue is available only for the older eShop version. ATM the VM will be optimised to work only with the latest version of eShop. For working with older eShop versions I've included some information in our README.rst, please follow the link for further information: https://github.com/OXID-eSales/oxvm_eshop#use-older-eshop-version

**Closed by rezonanc-oxid** 2016-11-17 20:55 UTC
Labels: bug, duplicate
